---
output: 
  github_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    fig.path = "man/figures/README-",
    fig.align="center",
    fig.width = 6,
    fig.height = 4)
```

<!-- README.md is generated from README.Rmd. Please edit that file -->

# hydflood

The R package **hydflood** is designed to compute flood extents and durations 
along the German federal waterways Elbe and Rhine.

## Installation

**hydflood** is currently not available from CRAN, but you can install the 
developmental version from Github with:

```{r install_git, eval = FALSE}
install.packages("devtools")
library(devtools)
devtools::install_github("bafg-bund/hydflood")
```

## Usage

The package **hydflood** is build around the packages `terra` and `hyd1d`.

```{r library, error = FALSE, message = FALSE, warning = FALSE, include = FALSE}
# standard library path for the installed local packages
R_version <- paste(sep = ".", R.Version()$major, R.Version()$minor)
lib <- paste0("~/R/", R_version, "/")
library(hydflood, lib.loc = lib)

# set english locale to produce english plot labels
Sys.setlocale(category = "LC_MESSAGES", locale = "en_US")
```

```{r usage, eval = TRUE, error = FALSE, warning = FALSE, message = FALSE}
# load the package
library(hydflood)

# import the raster data and create a raster stack
x <- hydSpatRaster(filename_dem = "data-raw/raster.dem.tif",
                   filename_csa = "data-raw/raster.csa.tif")

# create a temporal sequence
seq <- seq(as.Date("2016-12-01"), as.Date("2016-12-31"), by = "day")

# compute a flood duration
fd <- flood3(x = x, seq = seq)

# and plot it
plot(fd)
```
