---
title: "hydflood - map"
author: "Arnd Weber"
date: "`r Sys.Date()`"
output:
  html_document
---


``` {r map, fig.width = 6, fig.height = 8}
library(hydflood)
library(prettymapr)
library(ggplot2)
library(maps)
library(rosm)
library(sfheaders)

sf.afe_wgs84 <- st_transform(sf.af("Elbe"), st_crs(4326))
sf.afe_wgs84 <- sfheaders::sf_remove_holes(sf.afe_wgs84)
sf.afe_wgs84$river <- "Elbe"
coords_e <- st_coordinates(sf.afe_wgs84)
coords_e <- coords_e[coords_e[, "L1"] == 1, ]
cent_e <- st_centroid(sf.afe_wgs84, of_largest_polygon = TRUE)
cent_e$X <- st_coordinates(cent_e)[,"X"]
cent_e$Y <- st_coordinates(cent_e)[,"Y"]
sf.afr_wgs84 <- st_transform(sf.af("Rhine"), st_crs(4326))
sf.afr_wgs84 <- st_cast(sf.afr_wgs84, "MULTIPOLYGON")
sf.afr_wgs84$river <- "Rhine"
coords_r <- st_coordinates(sf.afr_wgs84)
coords_r <- coords_r[coords_r[, "L1"] == 1, ]
# cent_r <- st_centroid(sf.afr_wgs84, of_largest_polygon = TRUE)
# cent_r$X <- st_coordinates(cent_r)[,"X"]
# cent_r$Y <- st_coordinates(cent_r)[,"Y"]
sf.af <- rbind(sf.afe_wgs84, sf.afr_wgs84)
cent_r <- st_as_sf(data.frame(X = 8.2, Y = 50.5, river = "Rhine"),
                   coords = c("X", "Y"), remove = FALSE, crs = st_crs(4326))

sf.gs <- st_as_sf(df.gauging_station_data[
    which((df.gauging_station_data$river == "ELBE" |
           (df.gauging_station_data$river == "RHINE" & 
                df.gauging_station_data$km > 336)) &
              df.gauging_station_data$data_present),],
    coords = c("longitude", "latitude"), remove = FALSE, crs = st_crs(4326))
sf.gs$size <- 1
sf.gs$fill <- "blue"

# test areas
id.gs <- which(sf.gs$gauging_station %in% c("LENZEN", "DESSAU"))
sf.gs$size[id.gs] <- 2
sf.gs$fill[id.gs] <- "red"
# reference gauges "EMMERICH", "NEU DARCHAU"
id.gs <- which(sf.gs$gauging_station %in% c("EMMERICH", "NEU DARCHAU"))
sf.gs$size[id.gs] <- 3
sf.gs$fill[id.gs] <- "grey50"
# delft 3d "TANGERMUENDE", "GEESTHACHT"
id.gs <- which(sf.gs$gauging_station %in% c("TANGERMUENDE", "GEESTHACHT"))
sf.gs$size[id.gs] <- 4
sf.gs$fill[id.gs] <- "brown"

sf.gs$size <- as.factor(sf.gs$size)
sf.gs$fill <- as.factor(sf.gs$fill)

# Retrieve the map data
germany <- map_data("world", region = "Germany")
n <- max(germany$lat)
s <- min(germany$lat)
e <- max(germany$long)
w <- min(germany$long)

# centroid
library("rnaturalearth")
library("rnaturalearthdata")
library("rnaturalearthhires")
germany <- ne_countries(country = "Germany", scale = "large", returnclass = "sf")
germany_points <- st_centroid(germany)
germany_points$X <- st_coordinates(germany_points)[,"X"]
germany_points$Y <- st_coordinates(germany_points)[,"Y"]

# plot
bb <- makebbox(n, e, s, w)
col <- rgb(0, 0, 255, max = 255, alpha = 100, names = "blue40")
prettymap({
        osm.plot(bb, type = "cartolight", quiet = TRUE)
        osm.polygon(x = coords_e[, 1], y = coords_e[, 2], col = col)
        osm.polygon(x = coords_r[, 1], y = coords_r[, 2], col = col)
        osm.points(x = sf.gs$longitude, y = sf.gs$latitude, pch = 21,
                   bg = "blue", cex = 0.7)
        osm.points(x = sf.gs$longitude[id.gs], y = sf.gs$latitude[id.gs],
                   pch = 21, bg = "red", cex = 1)
        osm.text(x = sf.gs$longitude[id.gs], y = sf.gs$latitude[id.gs] - 0.1,
                 labels = sf.gs$gauging_station[id.gs], col = "red",
                 adj = c(1, 1), offset = 1)
        osm.text(germany_points$X, germany_points$Y, labels = "Germany",
                 cex = 1.5)
        osm.text(cent_e$X, cent_e$Y, labels = cent_e$river, cex = 1.2)
        osm.text(cent_r$X, cent_r$Y, labels = cent_r$river, cex = 1.2)
    },
    scale.style = "ticks", scale.tick.cex = 0.5, scale.plotepsg = 3857,
    drawarrow = TRUE, arrow.scale = 0.5
)
```


``` {r ggmap, fig.width = 6, fig.height = 8}
theme_set(theme_bw())

library("ggspatial")
library("ggmap")

col <- c("1" = "blue", "2" = "red")

ggplot() +
    geom_sf(data = germany) +
    geom_sf(data = sf.af, fill = "grey20", color = "grey20") +
    geom_sf(data = sf.gs, aes(colour = size), size = 1.5) +
    geom_sf(data = sf.gs[which(sf.gs$gauging_station == "DESSAU"),],
            fill = "red", color = "red", size = 2.5) +
    geom_text(data = sf.gs[which(sf.gs$gauging_station == "DESSAU"),],
                  aes(x = longitude - 0.2, y = latitude, label = gauging_station),
              color = "red", vjust = 2, size = 4) +
    geom_sf(data = sf.gs[which(sf.gs$gauging_station == "LENZEN"),],
            fill = "red", color = "red", size = 2.5) +
    geom_text(data = sf.gs[which(sf.gs$gauging_station == "LENZEN"),],
                  aes(x = longitude - 0.4, y = latitude, label = gauging_station),
              color = "red", vjust = 2, size = 4) +
    geom_sf(data = sf.gs[which(sf.gs$gauging_station == "EMMERICH"),],
            fill = "red", color = "red", size = 2.5) +
    geom_text(data = sf.gs[which(sf.gs$gauging_station == "EMMERICH"),],
                  aes(x = longitude + 1.05, y = latitude + 0.15,
                      label = gauging_station),
              color = "red", vjust = 2, size = 4) +
    geom_sf(data = sf.gs[which(sf.gs$gauging_station == "NEU DARCHAU"),],
            fill = "red", color = "red", size = 2.5) +
    geom_text(data = sf.gs[which(sf.gs$gauging_station == "NEU DARCHAU"),],
                  aes(x = longitude - 1.25, y = latitude + 0.10,
                      label = gauging_station),
              color = "red", vjust = 2, size = 4) +
    geom_sf(data = sf.gs[which(sf.gs$gauging_station == "TANGERMUENDE"),],
            fill = "red", color = "red", size = 2.5) +
    geom_text(data = sf.gs[which(sf.gs$gauging_station == "TANGERMUENDE"),],
                  aes(x = longitude + 1.3, y = latitude - 0.4,
                      label = "TANGERMÜNDE"),
              color = "red", vjust = -2, size = 4) +
    geom_sf(data = sf.gs[which(sf.gs$gauging_station == "GEESTHACHT"),],
            fill = "red", color = "red", size = 2.5) +
    geom_text(data = sf.gs[which(sf.gs$gauging_station == "GEESTHACHT"),],
                  aes(x = longitude + 1.1, y = latitude - 0.2,
                      label = gauging_station),
              color = "red", vjust = -2, size = 4) +
    geom_text(data = germany_points, aes(x = X, y = Y, label = name),
              fontface = "bold", size = 8, check_overlap = FALSE) +
    geom_text(data = cent_e, aes(x = X + 0.2, y = Y, label = river),
              size = 6, check_overlap = FALSE) +
    geom_text(data = cent_r, aes(x = X + 0.2, y = Y, label = river),
              size = 6, check_overlap = FALSE) +
    annotation_scale(location = "bl", width_hint = 0.5) +
    annotation_north_arrow(location = "tl", which_north = "true",
        style = north_arrow_fancy_orienteering) +
    labs(x = "Longitude", y = "Latitude", colour = "") +
    scale_color_manual(values = col, labels = c("gauging station", "test areas &\nreference gauges")) + 
    theme(legend.position = c(0.70, 0.97), legend.direction = "horizontal")
    #theme(legend.position = "bottom")
ggsave("map.pdf", width = 6, height = 8, dpi = 600)
```

``` {r ggmap_zoom, fig.width = 6, fig.height = 8}

ids <- seq(min(which(sf.gs$gauging_station %in% c("ROSSLAU", "GORLEBEN"))),
           max(which(sf.gs$gauging_station %in% c("ROSSLAU", "GORLEBEN"))),
           1)
bb <- st_bbox(sf.gs[ids,])
# bb <- ext(bb)
# bb <- st_bbox(c(xmin = bb["xmin"] - 0.1,
#                 xmax = bb["xmax"] + 0.1,
#                 ymax = bb["ymax"] + 0.1,
#                 ymin = bb["ymin"] - 0.1), crs = st_crs(4326))
# v <- c(bb$xmin - 0.1, bb$xmax + 0.1, bb$ymax + 0.1, bb$ymin - 0.1)
bb_zoom <- st_as_sfc(st_bbox(c("xmin" = 11.3 - 0.1,
                               "xmax" = 12.2 + 0.1,
                               "ymax" = 53.1 + 0.1,
                               "ymin" = 51.9 - 0.1), crs = st_crs(4326)))

# names(bb) <- c("xmin", "xmax", "ymin", "ymax")
# bb["xmin"] <- bb["xmin"] - 0.1
# bb["xmax"] <- bb["xmax"] + 0.1
# bb["ymin"] <- bb["ymin"] - 0.1
# bb["ymax"] <- bb["ymax"] + 0.1
#bb_zoom <- hydflood:::extent2polygon(bb, st_crs(4326))

col <- c("1" = "blue", "2" = "red", "3" = "grey50", "4" = "brown")

ggplot() +
    geom_sf(data = germany) +
    geom_sf(data = bb_zoom, linewidth = 0.5) + 
    geom_sf(data = sf.af, fill = "grey20", color = "grey20") +
    geom_sf(data = sf.gs, aes(colour = size), size = 1.5) +
    geom_sf(data = sf.gs[which(sf.gs$gauging_station == "DESSAU"),],
            fill = "red", color = "red", size = 2.5) +
    geom_text(data = sf.gs[which(sf.gs$gauging_station == "DESSAU"),],
                  aes(x = longitude - 0.2, y = latitude, label = gauging_station),
              color = "red", vjust = 2, size = 4) +
    geom_sf(data = sf.gs[which(sf.gs$gauging_station == "LENZEN"),],
            fill = "red", color = "red", size = 2.5) +
    geom_text(data = sf.gs[which(sf.gs$gauging_station == "LENZEN"),],
                  aes(x = longitude - 0.4, y = latitude, label = gauging_station),
              color = "red", vjust = 2, size = 4) +
    geom_sf(data = sf.gs[which(sf.gs$gauging_station == "EMMERICH"),],
            fill = "grey50", color = "grey50", size = 2.5) +
    geom_text(data = sf.gs[which(sf.gs$gauging_station == "EMMERICH"),],
                  aes(x = longitude + 1.05, y = latitude + 0.15,
                      label = gauging_station),
              color = "grey50", vjust = 2, size = 4) +
    geom_sf(data = sf.gs[which(sf.gs$gauging_station == "NEU DARCHAU"),],
            fill = "grey50", color = "grey50", size = 2.5) +
    geom_text(data = sf.gs[which(sf.gs$gauging_station == "NEU DARCHAU"),],
                  aes(x = longitude - 1.25, y = latitude + 0.10,
                      label = gauging_station),
              color = "grey50", vjust = 2, size = 4) +
    geom_sf(data = sf.gs[which(sf.gs$gauging_station == "TANGERMUENDE"),],
            fill = "brown", color = "brown", size = 2.5) +
    geom_text(data = sf.gs[which(sf.gs$gauging_station == "TANGERMUENDE"),],
                  aes(x = longitude + 1.3, y = latitude - 0.4,
                      label = "TANGERMÜNDE"),
              color = "brown", vjust = -2, size = 3) +
    geom_sf(data = sf.gs[which(sf.gs$gauging_station == "GEESTHACHT"),],
            fill = "brown", color = "brown", size = 2.5) +
    geom_text(data = sf.gs[which(sf.gs$gauging_station == "GEESTHACHT"),],
                  aes(x = longitude + 1.1, y = latitude - 0.2,
                      label = gauging_station),
              color = "brown", vjust = -2, size = 3) +
    geom_text(data = germany_points, aes(x = X, y = Y, label = name),
              fontface = "bold", size = 8, check_overlap = FALSE) +
    geom_text(data = cent_e, aes(x = X + 0.2, y = Y, label = river),
              size = 6, check_overlap = FALSE) +
    geom_text(data = cent_r, aes(x = X + 0.2, y = Y, label = river),
              size = 6, check_overlap = FALSE) +
    annotation_scale(location = "bl", width_hint = 0.5) +
    annotation_north_arrow(location = "tl", which_north = "true",
        style = north_arrow_fancy_orienteering) +
    labs(x = "Longitude", y = "Latitude", colour = "") +
    scale_color_manual(values = col, labels = c("gauging station", "test areas",
                                                "reference gauges", 
                                                "Delft3D FM model limits")) + 
    #theme(legend.position = c(0.30, 0.97), legend.direction = "horizontal")
    theme(legend.position = "bottom") #+ 
    # guides(color=guide_legend(nrow=2, byrow=TRUE)
ggsave("map_zoom.pdf", width = 6, height = 8, dpi = 600)
```


``` {r ggmap_zoomed, fig.width = 4, fig.height = 8}

ids <- seq(min(which(sf.gs$gauging_station %in% c("ROSSLAU", "GORLEBEN"))),
           max(which(sf.gs$gauging_station %in% c("ROSSLAU", "GORLEBEN"))), 1)

sf.afz <- st_intersection(sf.afe_wgs84, bb_zoom)
sf.gsz <- st_intersection(sf.gs, bb_zoom)

# delft 3d "TANGERMUENDE", "GEESTHACHT"
id.gs <- which(sf.gsz$gauging_station %in% c("TANGERMUENDE", "GEESTHACHT"))
sf.gsz$size[id.gs] <- 1
sf.gsz$fill[id.gs] <- "blue"
sf.gsz$size <- as.factor(sf.gsz$size)
sf.gsz$fill <- as.factor(sf.gsz$fill)

col <- c("1" = "blue", "2" = "red")

# axis
sf.axis <- st_zm(st_read("~/elbe1d/data-raw/VerkNetBWaStr", "verknet"))
sf.axis <- st_transform(sf.axis, crs = st_crs(4326))
sf.axisz <- st_intersection(sf.axis, bb_zoom)
sf.axisz <- sf.axisz[which(sf.axisz$BWASTR_ID == "0701"),]

# km
sf.km <- st_zm(st_read("~/elbe1d/data-raw/VerkNetBWaStr", "hectometer"))
sf.km <- sf.km[which(sf.km$M100 %in% c(300.0, 350.0, 400.0, 450.0, 500.0)),]
sf.km <- st_transform(sf.km, crs = st_crs(4326))
sf.km$longitude <- st_coordinates(sf.km)[,"X"]
sf.km$latitude <- st_coordinates(sf.km)[,"Y"]

# doc_dessau
sf.dessau <- st_read("~/hydflood/data-raw", "doc_mask_dessau")
sf.dessau <- st_transform(sf.dessau, crs = st_crs(4326))

# doc_dessau
sf.dessau <- st_read("~/hydflood/data-raw", "doc_mask_dessau")
sf.dessau <- st_transform(sf.dessau, crs = st_crs(4326))

# lenzen
sf.lenzen <- st_read(dsn = paste0("~/freigaben/Projekte/Elbe_U/EL_000_560_GEK_",
                                  "U2M3/DATENBASIS/GEODATEN/SONSTIGE/Planung_D",
                                    "eichrueckverlegung/Lenzen/Geodaten"),
                     layer = "UG_Lenzen")
sf.lenzen <- st_transform(sf.lenzen[1,], crs = st_crs(4326))
sf.lenzen_mask <- st_as_sfc(st_bbox(c(xmin = 263200, xmax = 264300,
                                      ymin = 5885600, ymax = 5886600),
                                    crs = st_crs(25833)))
sf.lenzen_mask <- st_transform(sf.lenzen_mask, crs = st_crs(4326))

# plot
ggplot() +
    geom_sf(data = sf.afz, fill = "grey90", color = "grey90") +
    geom_sf(data = sf.axisz, color = "blue", linewidth = 0.3) +
    geom_sf(data = sf.gsz, fill = "blue", color = "blue", size = 1) +
    geom_sf(data = sf.dessau, fill = NA, color = "black", linewidth = 0.5) +
    geom_sf(data = sf.lenzen, fill = "yellow", color = "yellow", linewidth = 0.5) +
    geom_sf(data = sf.km, fill = "darkblue", color = "darkblue", size = 0.6) +
    geom_text(data = sf.km, aes(x = longitude, y = latitude, label = M100),
              color = "darkblue", vjust = 2, size = 2) +
    geom_sf(data = sf.gsz[which(sf.gsz$gauging_station == "DESSAU"),],
            fill = "red", color = "red", size = 1.5) +
    geom_text(data = sf.gsz[which(sf.gsz$gauging_station == "DESSAU"),],
                  aes(x = longitude, y = latitude, label = gauging_station),
              color = "red", vjust = 2, size = 3) +
    geom_sf(data = sf.gsz[which(sf.gsz$gauging_station == "ROSSLAU"),],
            fill = "red", color = "red", size = 1.5) +
    geom_text(data = sf.gsz[which(sf.gsz$gauging_station == "ROSSLAU"),],
                  aes(x = longitude, y = latitude, label = gauging_station),
              color = "red", vjust = -1, size = 3) +
    geom_sf(data = sf.gsz[which(sf.gsz$gauging_station == "LENZEN"),],
            fill = "red", color = "red", size = 1.5) +
    geom_text(data = sf.gsz[which(sf.gsz$gauging_station == "LENZEN"),],
                  aes(x = longitude, y = latitude, label = gauging_station),
              color = "red", vjust = -1, size = 3) +
    geom_sf(data = sf.lenzen_mask, fill = NA, color = "black", linewidth = 0.5) +
    annotation_scale(location = "bl", width_hint = 0.5)
    
ggsave("map_zoomed.pdf", width = 6, height = 8, dpi = 600)
```
